
-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `sw_especialidad`
--

DROP TABLE IF EXISTS `sw_especialidad`;
CREATE TABLE `sw_especialidad` (
  `id_especialidad` int(11) NOT NULL,
  `id_tipo_educacion` int(11) NOT NULL,
  `es_nombre` varchar(64) CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `es_figura` varchar(50) NOT NULL,
  `es_abreviatura` varchar(15) NOT NULL,
  `es_orden` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `sw_especialidad`
--

INSERT INTO `sw_especialidad` (`id_especialidad`, `id_tipo_educacion`, `es_nombre`, `es_figura`, `es_abreviatura`, `es_orden`) VALUES
(1, 1, 'EGB SUPERIOR', 'EDUCACION BASICA SUPERIOR', 'EGB', 1),
(2, 2, 'CONTABILIDAD', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA', 2),
(3, 2, 'ADMINISTRACION DE SISTEMAS', 'ADMINISTRACION DE SISTEMAS', 'SIS', 3),
(4, 28, 'EDUCACION BASICA SUPERIOR', 'EDUCACION BASICA SUPERIOR', 'EGB', 1),
(5, 29, 'CONTABILIDAD', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA', 2),
(6, 29, 'ADMINISTRACION DE SISTEMAS', 'ADMINISTRACION DE SISTEMAS', 'SIS', 3),
(7, 30, 'CIENCIAS', 'BACHILLERATO EN CIENCIAS', 'BGU', 4),
(9, 31, 'EDUCACION BASICA SUPERIOR', 'EDUCACION BASICA SUPERIOR', 'EGB', 1),
(10, 32, 'CONTABILIDAD', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA', 2),
(11, 32, 'INFORMATICA', 'ADMINISTRACION DE SISTEMAS', 'SIS', 3),
(12, 33, 'CIENCIAS', 'BACHILLERATO EN CIENCIAS', 'BGU', 4),
(13, 34, 'EGB SUPERIOR', 'EDUCACION GENERAL BASICA SUPERIOR', 'EGB', 1),
(14, 36, 'BACHILLERATO GENERAL UNIFICADO', 'BACHILLERATO GENERAL UNIFICADO', 'BGU', 2),
(15, 35, 'BACHILLERATO TECNICO DE SERVICIOS', 'ADMINISTRACION DE SISTEMAS', 'SIS', 3),
(16, 35, 'BACHILLERATO TECNICO POLIVALENTE', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA', 4),
(18, 37, 'EGB SUPERIOR', 'EDUCACION GENERAL BASICA SUPERIOR', 'EGB', 1),
(19, 39, 'BACHILLERATO GENERAL UNIFICADO', 'BACHILLERATO GENERAL UNIFICADO', 'BGU', 2),
(20, 38, 'BACHILLERATO TECNICO DE SERVICIOS', 'ADMINISTRACION DE SISTEMAS', 'SISTEMAS', 3),
(21, 38, 'BACHILLERATO TECNICO POLIVALENTE', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA', 4),
(24, 40, 'EDUCACION GENERAL BASICA SUPERIOR', 'Educación General Básica Superior', 'EGBS', 1),
(25, 41, 'Área Técnica de Servicios', 'CONTABILIDAD', 'CONTA', 3),
(26, 41, 'Área Técnica de Servicios', 'INFORMÁTICA', 'INFO', 4),
(27, 42, 'BACHILLERATO GENERAL UNIFICADO', 'Bachillerato General Unificado', 'BGU', 2),
(28, 43, 'EGB SUPERIOR', 'EDUCACION GENERAL BASICA', 'EGBS', 0),
(29, 44, 'Área Técnica de Servicios', 'CONTABILIDAD', 'CONTA', 0),
(30, 45, 'BACHILLERATO GENERAL UNIFICADO', 'BACHILLERATO GENERAL UNIFICADO', 'BGU', 0),
(31, 44, 'Área Técnica de Servicios', 'INFORMATICA', 'INFO', 0),
(32, 46, 'EGB SUPERIOR', 'EDUCACION GENERAL BASICA SUPERIOR', 'EGBS', 0),
(33, 48, 'BACHILLERATO GENERAL UNIFICADO', 'BACHILLERATO GENERAL UNIFICADO', 'BGU', 0),
(34, 47, 'Área Técnica de Servicios', 'CONTABILIDAD', 'CONTA', 0),
(35, 47, 'Área Técnica de Servicios', 'INFORMATICA', 'INFO', 0),
(36, 49, 'EGB SUPERIOR', 'EDUCACION GENERAL BASICA SUPERIOR', 'EGBS', 1),
(37, 50, 'Área Técnica de Servicios', 'CONTABILIDAD', 'CONTA', 3),
(38, 50, 'Área Técnica de Servicios', 'INFORMATICA', 'INFO', 4),
(39, 51, 'BACHILLERATO GENERAL UNIFICADO', 'BACHILLERATO GENERAL UNIFICADO', 'BGU', 2),
(40, 52, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 'EGBS INTENSIVA', 'EGBS INTENSIVA', 0),
(41, 53, 'BACHILLERATO GENERAL UNIFICADO', 'BACHILLERATO GENERAL UNIFICADO', 'BGUI', 0),
(42, 54, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 'BGU INTENSIVO', 'BGUI', 0),
(43, 55, 'Área Técnica de Servicios', 'CONTABILIDAD', 'CONTA', 1),
(44, 55, 'Área Técnica de Servicios', 'INFORMATICA', 'INFO', 2),
(45, 56, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 'EGBS INTENSIVA', 'EGBS INTENSIVA', 0),
(46, 57, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 'BGU INTENSIVO', 'BGUI', 0),
(47, 58, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 'BGU INTENSIVO', 'BGUI', 0),
(49, 61, 'Área Técnica de Servicios', 'CONTABILIDAD', 'CONTA', 1),
(50, 61, 'Área Técnica TICs', 'INFORMATICA', 'INFO', 2),
(51, 62, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 'BGU INTENSIVO', 'BGUI', 1),
(52, 63, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 'EGBS INTENSIVA', 'EGBS INTENSIVA', 1),
(53, 64, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 'EGBS INTENSIVA', 'EGBS INTENSIVA', 1),
(54, 65, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 'BGU INTENSIVO', 'BGUI', 1),
(55, 66, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 'EGBS INTENSIVA', 'EGBS INTENSIVA', 1),
(56, 67, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 'BGU INTENSIVO', 'BGUI', 1),
(57, 68, 'Área Técnica de Servicios', 'CONTABILIDAD', 'CONTA', 1),
(58, 68, 'Área Técnica TICs', 'INFORMATICA', 'INFO', 2);
