
-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `sw_tipo_educacion`
--

DROP TABLE IF EXISTS `sw_tipo_educacion`;
CREATE TABLE `sw_tipo_educacion` (
  `id_tipo_educacion` int(11) NOT NULL,
  `id_periodo_lectivo` int(11) NOT NULL,
  `te_nombre` varchar(48) CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `te_bachillerato` tinyint(11) NOT NULL,
  `te_orden` tinyint(4) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `sw_tipo_educacion`
--

INSERT INTO `sw_tipo_educacion` (`id_tipo_educacion`, `id_periodo_lectivo`, `te_nombre`, `te_bachillerato`, `te_orden`) VALUES
(1, 1, 'EDUCACION BASICA SUPERIOR', 0, 1),
(2, 1, 'BACHILLERATO TECNICO', 1, 2),
(5, 1, 'BACHILLERATO EN CIENCIAS', 1, 3),
(28, 2, 'EDUCACION BASICA SUPERIOR', 0, 1),
(29, 2, 'BACHILLERATO TECNICO', 1, 2),
(30, 2, 'BACHILLERATO EN CIENCIAS', 1, 3),
(31, 3, 'EDUCACION BASICA SUPERIOR', 0, 1),
(32, 3, 'BACHILLERATO TECNICO', 1, 2),
(33, 3, 'BACHILLERATO EN CIENCIAS', 1, 3),
(34, 4, 'EDUCACION BASICA SUPERIOR', 0, 1),
(35, 4, 'BACHILLERATO TECNICO', 1, 2),
(36, 4, 'BACHILLERATO GENERAL UNIFICADO', 1, 3),
(37, 5, 'EDUCACION BASICA SUPERIOR', 0, 1),
(38, 5, 'BACHILLERATO TECNICO', 1, 2),
(39, 5, 'BACHILLERATO GENERAL UNIFICADO', 1, 3),
(40, 6, 'EDUCACION BASICA SUPERIOR', 0, 1),
(41, 6, 'BACHILLERATO TECNICO', 1, 2),
(42, 6, 'BACHILLERATO GENERAL UNIFICADO', 1, 3),
(43, 7, 'EDUCACION BASICA SUPERIOR', 0, 1),
(44, 7, 'BACHILLERATO TECNICO', 1, 2),
(45, 7, 'BACHILLERATO EN CIENCIAS', 1, 3),
(46, 8, 'EDUCACION BASICA SUPERIOR', 0, 1),
(47, 8, 'BACHILLERATO TECNICO', 1, 2),
(48, 8, 'BACHILLERATO GENERAL UNIFICADO', 1, 3),
(49, 9, 'EDUCACION BASICA SUPERIOR', 0, 1),
(50, 9, 'BACHILLERATO TECNICO', 1, 3),
(51, 9, 'BACHILLERATO GENERAL UNIFICADO', 1, 2),
(52, 10, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 0, 1),
(53, 11, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 1, 1),
(54, 12, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 1, 1),
(55, 13, 'BACHILLERATO TECNICO', 1, 1),
(56, 14, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 0, 1),
(57, 15, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 1, 1),
(58, 16, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 1, 1),
(61, 17, 'BACHILLERATO TECNICO', 1, 1),
(62, 19, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 1, 1),
(63, 18, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 0, 1),
(64, 20, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 0, 1),
(65, 21, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 1, 1),
(66, 24, 'EDUCACION GENERAL BASICA SUPERIOR INTENSIVA', 0, 1),
(67, 25, 'BACHILLERATO GENERAL UNIFICADO INTENSIVO', 1, 1),
(68, 26, 'BACHILLERATO TECNICO', 1, 1);
