
DROP TABLE IF EXISTS `sw_especialidad`;
CREATE TABLE `sw_especialidad` (
  `id_especialidad` int(11) NOT NULL,
  `id_tipo_educacion` int(11) NOT NULL,
  `es_nombre` varchar(64) CHARACTER SET latin1 COLLATE latin1_spanish_ci NOT NULL,
  `es_figura` varchar(50) NOT NULL,
  `es_abreviatura` varchar(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `sw_especialidad` (`id_especialidad`, `id_tipo_educacion`, `es_nombre`, `es_figura`, `es_abreviatura`) VALUES
(1, 1, 'NINGUNA', 'EDUCACION BASICA SUPERIOR', 'EGB'),
(2, 2, 'CONTABILIDAD', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA'),
(3, 2, 'ADMINISTRACION DE SISTEMAS', 'ADMINISTRACION DE SISTEMAS', 'SIS'),
(4, 3, 'EDUCACION BASICA SUPERIOR', 'EDUCACION BASICA SUPERIOR', 'EGB'),
(5, 4, 'CONTABILIDAD', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA'),
(6, 4, 'ADMINISTRACION DE SISTEMAS', 'ADMINISTRACION DE SISTEMAS', 'SIS'),
(7, 5, 'CIENCIAS', 'BACHILLERATO EN CIENCIAS', 'BGU'),
(9, 6, 'EDUCACION BASICA SUPERIOR', 'EDUCACION BASICA SUPERIOR', 'EGB'),
(10, 7, 'CONTABILIDAD', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA'),
(11, 7, 'INFORMATICA', 'ADMINISTRACION DE SISTEMAS', 'SIS'),
(12, 8, 'CIENCIAS', 'BACHILLERATO EN CIENCIAS', 'BGU'),
(13, 9, 'EGB SUPERIOR', 'EDUCACION GENERAL BASICA SUPERIOR', 'EGB'),
(14, 10, 'BACHILLERATO GENERAL UNIFICADO', 'BACHILLERATO GENERAL UNIFICADO', 'BGU'),
(15, 11, 'BACHILLERATO TECNICO DE SERVICIOS', 'ADMINISTRACION DE SISTEMAS', 'SIS'),
(16, 11, 'BACHILLERATO TECNICO POLIVALENTE', 'CONTABILIDAD Y ADMINISTRACION', 'CONTA'),
(17, 12, 'BACHILLERATO VIRTUAL', 'BACHILLERATO VIRTUAL', 'BV'),
(18, 13, 'EGB SUPERIOR', 'Educación General Básica Superior', 'EGB'),
(19, 14, 'BACHILLERATO GENERAL UNIFICADO', 'Bachillerato General Unificado', 'BGU'),
(20, 15, 'BACHILLERATO TECNICO DE SERVICIOS', 'Administración de Sistemas', 'SISTEMAS'),
(21, 15, 'BACHILLERATO TECNICO POLIVALENTE', 'Contabilidad y Administración', 'CONTA'),
(24, 17, 'EGB SUPERIOR', 'Educación General Básica Superior', 'EGB'),
(25, 18, 'Área Técnica de Servicios', 'Contabilidad', 'CONTA'),
(26, 18, 'Área Técnica de Servicios', 'Informática', 'INFO'),
(27, 19, 'BACHILLERATO GENERAL UNIFICADO', 'Bachillerato General Unificado', 'BGU');
